### ISSUE TITLE
Use script to collect congressional candidate's data

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/2022-Election-Material#1]
As we talked about on the call 
- Try to execute the script
- If successful - you will get a new dataframe (csv) with candidates names, positions, twitter accounts, and websites, etc
- Upload the data to this repository and then let me know

Note - don't spend more than 5 hours trying to get this to work - if you get stuck reach out and we can help you debug.

**Comment by peiwenf** [comment]
I have modified the script and gathered data at November 9th
